services:
  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - 23701:23701
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME: root
      - ME_CONFIG_MONGODB_ADMINPASSWORD: example
      - ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
